version: "3.9"

services:
  telegram-api:
    build: .
    container_name: telegram-api
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: "33199374"
      TELEGRAM_API_HASH: "673acffb436789541a376b551066057b"
      TELEGRAM_WORK_DIR: "data"
      TELEGRAM_LOCAL: 1  # allow files >20mb
    volumes:
      - telegram-data:/data
    networks:
      - shared_net
    ports:
      - "8081:8081"


volumes:
  telegram-data:
   external: true
   name: telegram_data
networks:
  shared_net:
    external: true